### ISSUE TITLE
Background image doesn't show

### ISSUE THREAD

**Issue by Dash-gr** [Dash-gr/dash-gr.github.io#7]

**Comment by Steve0Greatness** [comment]
```css
body {
  background-image: url("/assets/background.jpg");
}
```
Also, in the 2 buttons, make sure to add a `#` before the hexcode color values so that css will know that it's a color value.
